import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1769894923021 implements MigrationInterface {
    name = 'InitialSchema1769894923021'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."circle_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TABLE "circle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "description" text, "location" character varying, "gender" "public"."circle_gender_enum" NOT NULL DEFAULT 'MALE', "teacher_id" uuid, "mosque_id" uuid NOT NULL, CONSTRAINT "PK_9acc76020bf08433e769e72deb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18f21ba41c7762c679ba798d59" ON "circle" ("teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9e1bcb8a6a4254bce71d51089" ON "circle" ("mosque_id") `);
        await queryRunner.query(`CREATE TABLE "student" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "phone" character varying, "dob" date, "address" character varying, "notes" text, "guardian_name" character varying, "guardian_phone" character varying, "circle_id" uuid, "total_points" integer NOT NULL DEFAULT '0', "user_id" uuid, "username" character varying, "mosque_id" uuid NOT NULL, CONSTRAINT "UQ_cdf9742519b09580df0bc13cb18" UNIQUE ("username"), CONSTRAINT "REL_0cc43638ebcf41dfab27e62dc0" UNIQUE ("user_id"), CONSTRAINT "PK_3d8016e1cb58429474a3c041904" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f07a92b3d43e2f27aa300b92ed" ON "student" ("circle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cc43638ebcf41dfab27e62dc0" ON "student" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdf9742519b09580df0bc13cb1" ON "student" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed8cdc082b96b32871be408caa" ON "student" ("mosque_id") `);
        await queryRunner.query(`CREATE TYPE "public"."exam_status_enum" AS ENUM('PENDING', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "exam" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "student_id" uuid NOT NULL, "examiner_id" uuid, "date" date NOT NULL, "juz_number" integer NOT NULL, "attempt_number" integer NOT NULL DEFAULT '1', "current_part_score" double precision, "cumulative_score" double precision, "final_score" double precision, "tested_parts" integer array NOT NULL DEFAULT '{}', "passed" boolean, "status" "public"."exam_status_enum" NOT NULL DEFAULT 'PENDING', "notes" text, "mosque_id" uuid NOT NULL, CONSTRAINT "PK_56071ab3a94aeac01f1b5ab74aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77a5e7c775a0d8fa602d7547f1" ON "exam" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c27205a202e6680a28956b0bdf" ON "exam" ("examiner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8b5c62e0598bd5b93e582894" ON "exam" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ffcbb0c9b072b2f4e43ad0054" ON "exam" ("mosque_id") `);
        await queryRunner.query(`CREATE TYPE "public"."session_status_enum" AS ENUM('OPEN', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "date" date NOT NULL, "notes" text, "status" "public"."session_status_enum" NOT NULL DEFAULT 'OPEN', "circle_id" uuid NOT NULL, "mosque_id" uuid NOT NULL, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7fb8edba31626376965c54c43" ON "session" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba6523542a1603a43a42a70dfe" ON "session" ("circle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a55b737813a57f32fb7ab5216" ON "session" ("mosque_id") `);
        await queryRunner.query(`CREATE TABLE "mosque" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "code" character varying(6) NOT NULL, CONSTRAINT "UQ_7cda663d4ba6b4c074fca5cdb2d" UNIQUE ("code"), CONSTRAINT "PK_2395735f8a8b5c139dc33c30f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cda663d4ba6b4c074fca5cdb2" ON "mosque" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('ADMIN', 'TEACHER', 'SUPERVISOR', 'STUDENT', 'EXAMINER')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "email" character varying NOT NULL, "password" character varying NOT NULL, "full_name" character varying NOT NULL, "phone_number" character varying(20) NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'TEACHER', "mosque_id" uuid, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc03f8a361fd63b2a76849328a" ON "user" ("mosque_id") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'PRESENT', "session_id" uuid NOT NULL, "student_id" uuid NOT NULL, CONSTRAINT "UQ_cb17b7626e1fd2e14ee9ba936b0" UNIQUE ("session_id", "student_id"), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5940f7beb6d791a618dbf88361" ON "attendance" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6200532f3ef99f639a27bdcae7" ON "attendance" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."surah_type_enum" AS ENUM('QURAN', 'HADITH', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "surah" ("id" SERIAL NOT NULL, "number" integer NOT NULL, "name_arabic" character varying NOT NULL, "name_english" character varying NOT NULL, "verse_count" integer NOT NULL, "start_page" integer NOT NULL DEFAULT '1', "end_page" integer NOT NULL DEFAULT '1', "type" "public"."surah_type_enum" NOT NULL DEFAULT 'QURAN', CONSTRAINT "UQ_193985671b80b51677db96c2f53" UNIQUE ("number"), CONSTRAINT "PK_a94c4dd903afb7159574c548b74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_193985671b80b51677db96c2f5" ON "surah" ("number") `);
        await queryRunner.query(`CREATE TYPE "public"."recitation_type_enum" AS ENUM('NEW_LESSON', 'REVIEW')`);
        await queryRunner.query(`CREATE TYPE "public"."recitation_quality_enum" AS ENUM('EXCELLENT', 'VERY_GOOD', 'GOOD', 'ACCEPTABLE', 'POOR')`);
        await queryRunner.query(`CREATE TABLE "recitation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "type" "public"."recitation_type_enum" NOT NULL, "quality" "public"."recitation_quality_enum" NOT NULL, "page_number" integer NOT NULL, "mistakes_count" integer NOT NULL DEFAULT '0', "notes" text, "student_id" uuid NOT NULL, "session_id" uuid NOT NULL, "surah_id" integer, CONSTRAINT "PK_2fbd7b203a9927d06ad6c21fe4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72cd25f3b5e265920744e6e679" ON "recitation" ("page_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1645a1efed203a7d07aa1216b" ON "recitation" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4388d8eebb3c7ed94f85b64d74" ON "recitation" ("session_id") `);
        await queryRunner.query(`CREATE TYPE "public"."point_transaction_source_type_enum" AS ENUM('RECITATION', 'ATTENDANCE', 'MANUAL_REWARD', 'MANUAL_PENALTY')`);
        await queryRunner.query(`CREATE TABLE "point_transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "amount" integer NOT NULL, "reason" character varying NOT NULL, "source_type" "public"."point_transaction_source_type_enum" NOT NULL, "student_id" uuid NOT NULL, "session_id" uuid, "awarded_by_id" uuid, CONSTRAINT "PK_b56b792bcf7f60a32758005caf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc8062092c9f3669917500c96c" ON "point_transaction" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c090a190eb8253450a5b66986c" ON "point_transaction" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f90f1871fe96019e4df79f467" ON "point_transaction" ("awarded_by_id") `);
        await queryRunner.query(`CREATE TABLE "point_rule" ("id" SERIAL NOT NULL, "key" character varying NOT NULL, "description" character varying NOT NULL, "points" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8a6551868d08f942914519d40e8" UNIQUE ("key"), CONSTRAINT "PK_cf38a25767f842df183d33d96f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a6551868d08f942914519d40e" ON "point_rule" ("key") `);
        await queryRunner.query(`CREATE TYPE "public"."exam_question_type_enum" AS ENUM('CURRENT_PART', 'CUMULATIVE')`);
        await queryRunner.query(`CREATE TABLE "exam_question" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "exam_id" uuid NOT NULL, "type" "public"."exam_question_type_enum" NOT NULL, "question_juz_number" integer, "question_text" text, "mistakes_count" integer NOT NULL DEFAULT '0', "max_score" integer NOT NULL, "achieved_score" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_a1c309a024492d50f43ff8b4c67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6664355ca7a2d081b4d89cc1ea" ON "exam_question" ("exam_id") `);
        await queryRunner.query(`ALTER TABLE "circle" ADD CONSTRAINT "FK_18f21ba41c7762c679ba798d591" FOREIGN KEY ("teacher_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle" ADD CONSTRAINT "FK_f9e1bcb8a6a4254bce71d51089f" FOREIGN KEY ("mosque_id") REFERENCES "mosque"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student" ADD CONSTRAINT "FK_f07a92b3d43e2f27aa300b92ed1" FOREIGN KEY ("circle_id") REFERENCES "circle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student" ADD CONSTRAINT "FK_0cc43638ebcf41dfab27e62dc09" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student" ADD CONSTRAINT "FK_ed8cdc082b96b32871be408caab" FOREIGN KEY ("mosque_id") REFERENCES "mosque"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam" ADD CONSTRAINT "FK_77a5e7c775a0d8fa602d7547f1e" FOREIGN KEY ("student_id") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam" ADD CONSTRAINT "FK_c27205a202e6680a28956b0bdff" FOREIGN KEY ("examiner_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam" ADD CONSTRAINT "FK_3ffcbb0c9b072b2f4e43ad00544" FOREIGN KEY ("mosque_id") REFERENCES "mosque"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_ba6523542a1603a43a42a70dfef" FOREIGN KEY ("circle_id") REFERENCES "circle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_8a55b737813a57f32fb7ab52160" FOREIGN KEY ("mosque_id") REFERENCES "mosque"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_bc03f8a361fd63b2a76849328a6" FOREIGN KEY ("mosque_id") REFERENCES "mosque"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_5940f7beb6d791a618dbf88361e" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_6200532f3ef99f639a27bdcae7f" FOREIGN KEY ("student_id") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recitation" ADD CONSTRAINT "FK_f1645a1efed203a7d07aa1216b7" FOREIGN KEY ("student_id") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recitation" ADD CONSTRAINT "FK_4388d8eebb3c7ed94f85b64d74b" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recitation" ADD CONSTRAINT "FK_ba4bd93b098d419642102da4a2a" FOREIGN KEY ("surah_id") REFERENCES "surah"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_transaction" ADD CONSTRAINT "FK_dc8062092c9f3669917500c96c1" FOREIGN KEY ("student_id") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point_transaction" ADD CONSTRAINT "FK_c090a190eb8253450a5b66986c9" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam_question" ADD CONSTRAINT "FK_6664355ca7a2d081b4d89cc1ea3" FOREIGN KEY ("exam_id") REFERENCES "exam"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "exam_question" DROP CONSTRAINT "FK_6664355ca7a2d081b4d89cc1ea3"`);
        await queryRunner.query(`ALTER TABLE "point_transaction" DROP CONSTRAINT "FK_c090a190eb8253450a5b66986c9"`);
        await queryRunner.query(`ALTER TABLE "point_transaction" DROP CONSTRAINT "FK_dc8062092c9f3669917500c96c1"`);
        await queryRunner.query(`ALTER TABLE "recitation" DROP CONSTRAINT "FK_ba4bd93b098d419642102da4a2a"`);
        await queryRunner.query(`ALTER TABLE "recitation" DROP CONSTRAINT "FK_4388d8eebb3c7ed94f85b64d74b"`);
        await queryRunner.query(`ALTER TABLE "recitation" DROP CONSTRAINT "FK_f1645a1efed203a7d07aa1216b7"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_6200532f3ef99f639a27bdcae7f"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_5940f7beb6d791a618dbf88361e"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_bc03f8a361fd63b2a76849328a6"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_8a55b737813a57f32fb7ab52160"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_ba6523542a1603a43a42a70dfef"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP CONSTRAINT "FK_3ffcbb0c9b072b2f4e43ad00544"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP CONSTRAINT "FK_c27205a202e6680a28956b0bdff"`);
        await queryRunner.query(`ALTER TABLE "exam" DROP CONSTRAINT "FK_77a5e7c775a0d8fa602d7547f1e"`);
        await queryRunner.query(`ALTER TABLE "student" DROP CONSTRAINT "FK_ed8cdc082b96b32871be408caab"`);
        await queryRunner.query(`ALTER TABLE "student" DROP CONSTRAINT "FK_0cc43638ebcf41dfab27e62dc09"`);
        await queryRunner.query(`ALTER TABLE "student" DROP CONSTRAINT "FK_f07a92b3d43e2f27aa300b92ed1"`);
        await queryRunner.query(`ALTER TABLE "circle" DROP CONSTRAINT "FK_f9e1bcb8a6a4254bce71d51089f"`);
        await queryRunner.query(`ALTER TABLE "circle" DROP CONSTRAINT "FK_18f21ba41c7762c679ba798d591"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6664355ca7a2d081b4d89cc1ea"`);
        await queryRunner.query(`DROP TABLE "exam_question"`);
        await queryRunner.query(`DROP TYPE "public"."exam_question_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a6551868d08f942914519d40e"`);
        await queryRunner.query(`DROP TABLE "point_rule"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f90f1871fe96019e4df79f467"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c090a190eb8253450a5b66986c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc8062092c9f3669917500c96c"`);
        await queryRunner.query(`DROP TABLE "point_transaction"`);
        await queryRunner.query(`DROP TYPE "public"."point_transaction_source_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4388d8eebb3c7ed94f85b64d74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1645a1efed203a7d07aa1216b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72cd25f3b5e265920744e6e679"`);
        await queryRunner.query(`DROP TABLE "recitation"`);
        await queryRunner.query(`DROP TYPE "public"."recitation_quality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recitation_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_193985671b80b51677db96c2f5"`);
        await queryRunner.query(`DROP TABLE "surah"`);
        await queryRunner.query(`DROP TYPE "public"."surah_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6200532f3ef99f639a27bdcae7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5940f7beb6d791a618dbf88361"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc03f8a361fd63b2a76849328a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cda663d4ba6b4c074fca5cdb2"`);
        await queryRunner.query(`DROP TABLE "mosque"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a55b737813a57f32fb7ab5216"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba6523542a1603a43a42a70dfe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7fb8edba31626376965c54c43"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP TYPE "public"."session_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ffcbb0c9b072b2f4e43ad0054"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8b5c62e0598bd5b93e582894"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c27205a202e6680a28956b0bdf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77a5e7c775a0d8fa602d7547f1"`);
        await queryRunner.query(`DROP TABLE "exam"`);
        await queryRunner.query(`DROP TYPE "public"."exam_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed8cdc082b96b32871be408caa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdf9742519b09580df0bc13cb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cc43638ebcf41dfab27e62dc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f07a92b3d43e2f27aa300b92ed"`);
        await queryRunner.query(`DROP TABLE "student"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9e1bcb8a6a4254bce71d51089"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18f21ba41c7762c679ba798d59"`);
        await queryRunner.query(`DROP TABLE "circle"`);
        await queryRunner.query(`DROP TYPE "public"."circle_gender_enum"`);
    }

}
