/**
 * Admin Gamification Hooks
 *
 * Quests, Milestones, Achievements, Seasonal Events, and Store Fulfillments.
 * Standard CRUD hooks are generated by the factory; custom/nested queries
 * are hand-written below.
 *
 * All exported names are unchanged so existing component imports keep
 * working without modification.
 */

import { QuestCategory, QuestFrequency } from "@halaqat/types";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { apiClient } from "@/lib/api-client";
import { queryKeys } from "@/lib/query-keys";
import type { CreateAchievementInput } from "@/lib/schemas/achievement";
import type { CreateEventInput } from "@/lib/schemas/event";
import type { CreateMilestoneInput } from "@/lib/schemas/milestone";
import type { CreateQuestInput } from "@/lib/schemas/quest";

import { createResourceHooks } from "./factories/create-resource-hooks";

// ── Types (unchanged from original) ───────────────────────────────────────

export type RewardType = "BONUS_XP" | "AVATAR_FRAME" | "TITLE";
export type AchievementCriteriaType =
  | "TOTAL_QUESTS_CATEGORY"
  | "STREAK_DAYS"
  | "TOTAL_XP";

export interface Quest {
  id: string;
  title: string;
  description: string | null;
  category: QuestCategory;
  frequency: QuestFrequency;
  xpReward: number;
  icon: string;
  isActive: boolean;
  target: number;
  targetUnit: string | null;
  createdAt: string;
}

export interface MilestoneReward {
  id: string;
  targetLevel: number;
  title: string;
  rewardType: RewardType;
  rewardValue: string;
  createdAt: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  badgeIcon: string;
  criteriaType: AchievementCriteriaType;
  criteriaTarget: number;
  criteriaCategory: QuestCategory | null;
  createdAt: string;
  rarity: "COMMON" | "RARE" | "EPIC" | "LEGENDARY";
}

export interface SeasonalEvent {
  id: string;
  name: string;
  nameAr: string;
  description: string | null;
  descriptionAr: string | null;
  startsAt: string;
  endsAt: string;
  xpMultiplier: number;
  icon: string;
  themeColor: string;
  bannerUrl: string | null;
  isActive: boolean;
  createdAt: string;
}

export interface EventQuest {
  id: string;
  eventId: string;
  questId: string;
  bonusXp: number;
  quest: Quest;
}

export interface FulfillmentItem {
  id: string;
  studentName: string;
  studentId: string;
  itemName: string;
  itemIcon: string;
  xpSpent: number;
  purchasedAt: string;
  fulfillmentStatus: "pending" | "fulfilled" | "cancelled";
}

// ── Factory hooks ─────────────────────────────────────────────────────────

const questHooks = createResourceHooks<Quest, CreateQuestInput, CreateQuestInput>({
  baseUrl: "/gamification/admin/quests",
  keys: queryKeys.adminQuests,
});

export const useAdminQuests = questHooks.useList;
export const useCreateQuest = questHooks.useCreate;
export const useUpdateQuest = questHooks.useUpdate;
export const useDeleteQuest = questHooks.useRemove;

const milestoneHooks = createResourceHooks<
  MilestoneReward,
  CreateMilestoneInput,
  CreateMilestoneInput
>({
  baseUrl: "/gamification/admin/milestones",
  keys: queryKeys.adminMilestones,
});

export const useAdminMilestones = milestoneHooks.useList;
export const useCreateMilestone = milestoneHooks.useCreate;
export const useUpdateMilestone = milestoneHooks.useUpdate;
export const useDeleteMilestone = milestoneHooks.useRemove;

const achievementHooks = createResourceHooks<
  Achievement,
  CreateAchievementInput,
  CreateAchievementInput
>({
  baseUrl: "/gamification/admin/achievements",
  keys: queryKeys.adminAchievements,
});

export const useAdminAchievements = achievementHooks.useList;
export const useCreateAchievement = achievementHooks.useCreate;
export const useUpdateAchievement = achievementHooks.useUpdate;
export const useDeleteAchievement = achievementHooks.useRemove;

const eventHooks = createResourceHooks<
  SeasonalEvent,
  CreateEventInput,
  CreateEventInput
>({
  baseUrl: "/gamification/admin/events",
  keys: queryKeys.adminEvents,
});

export const useAdminEvents = eventHooks.useList;
export const useCreateEvent = eventHooks.useCreate;
export const useUpdateEvent = eventHooks.useUpdate;
export const useDeleteEvent = eventHooks.useRemove;

// ── Custom: Event ↔ Quest association (non-CRUD, stays hand-written) ───────

export function useEventQuests(eventId: string) {
  return useQuery({
    queryKey: queryKeys.adminEvents.quests(eventId),
    queryFn: () =>
      apiClient.get<EventQuest[]>(`/gamification/admin/events/${eventId}/quests`),
    enabled: !!eventId,
  });
}

export function useAddQuestToEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({
      eventId,
      questId,
      bonusXp,
    }: {
      eventId: string;
      questId: string;
      bonusXp?: number;
    }) =>
      apiClient.post<EventQuest>(`/gamification/admin/events/${eventId}/quests`, {
        questId,
        ...(bonusXp !== undefined ? { bonusXp } : {}),
      }),
    onSuccess: (_, variables) => {
      qc.invalidateQueries({
        queryKey: queryKeys.adminEvents.quests(variables.eventId),
      });
    },
  });
}

export function useRemoveQuestFromEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ eventId, questId }: { eventId: string; questId: string }) =>
      apiClient.delete(`/gamification/admin/events/${eventId}/quests/${questId}`),
    onSuccess: (_, variables) => {
      qc.invalidateQueries({
        queryKey: queryKeys.adminEvents.quests(variables.eventId),
      });
    },
  });
}

// ── Store Fulfillments (admin-only, patch only) ────────────────────────────

export function usePendingFulfillments() {
  return useQuery({
    queryKey: queryKeys.adminFulfillments.list(),
    queryFn: () =>
      apiClient.get<FulfillmentItem[]>("/gamification/admin/pending-fulfillments"),
  });
}

export function useUpdateFulfillment() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({
      id,
      status,
      notes,
    }: {
      id: string;
      status: "fulfilled" | "cancelled";
      notes?: string;
    }) =>
      apiClient.patch(`/gamification/admin/fulfillments/${id}`, {
        status,
        ...(notes !== undefined ? { notes } : {}),
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: queryKeys.adminFulfillments.all });
    },
  });
}
